### ISSUE TITLE
Alert doesn't let user to fill complete information

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/mobile#5271]
## Describe the bug

While creating new duplicate patient, while adding information the duplicate alert appears in the middle of information input and it disturb the form filling process and redirect back to the list and don't let fill the full information on the form.

### To reproduce

Steps to reproduce the behaviour:

1. Go to mobile site
2. Click on `Dispensing`
3. Click on `New patient`
4. Try creating new duplicate patient
5. See error

Video here

https://github.com/openmsupply/mobile/assets/115983430/910dd3f8-76da-4c71-9188-438f18e0d15e

### Expected behaviour

Should let fill the full information

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version: v8.6.6
- Tablet model:
- OS version:

### Additional context

Noticed while testing [THIS](https://github.com/openmsupply/mobile/pull/5238)

**Comment by DhanyaHerath** [comment]
Good catch thank you @AnushaUp!

**Comment by ujwalSussol** [comment]
@arjunSussol  :  have you written some code on this. Could you publish it so that folks can see progress.  Perhaps you can write `Not Ready for Review`  ... @sanjeevsussol  please create a label `Draft:Don't Review`  ...  if a PR is likely to take long then we may have to use this approach so that folks in NZ know that work is being done.

**Comment by AnushaUp** [comment]
## Testing
Tested in `Tested in Mobile v8.6.6-rc01`
- [ ] Dispensary > Try to create a duplicate patient having same firstName, lastName, and DoB
- [ ] There should be alert with confirmation to create duplicate patient.
- [ ] If click Cancel then cancel the process and return back to patient list window
- [ ] If click OK then remains in the same window and fill the required fields then create patient.
