### ISSUE TITLE
MAM requisition quantity not matching between mobile and desktop

### ISSUE THREAD

**Issue by sah-arjun** [msupply-foundation/mobile#5299]
## Describe the bug

A mobile site (KyarinSeikGyi) requested 7500 strips of STRIP blood glucose via the mSupply tablet.
However, in the mSupply desktop (YGN supplying store), it showed only 7 for this item, while the rest of the items are correct in the requested amount.

### To reproduce

Steps to reproduce the behaviour:

1. setup mobile with MAM above site with the mobile v5.1.2

### Proposed Solution

Leave if you don't know how to fix/implement. Edit this issue description and explain here if you know the best path of implementing the fix within the codebase.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by arjunSussol** [comment]
Can't recreate it after testing with MAM data and latest mobile and desktop.
So, this could be due to the data issue or older bugs which should be fixed.
So, closing this.
