### ISSUE TITLE
Display age below 1 year old in months and days

### ISSUE THREAD

**Issue by arjunSussol** [msupply-foundation/mobile#5308]
## Is your feature request related to a problem? Please describe.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**

## Describe the solution you'd like
For newly born baby the age shown as zero year. So, better to display months and days for below 1 years old

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

**A clear and concise description of any alternative solutions or features you've considered.**

## Additional context

**Add any other context or screenshots about the feature request here.**

## MoneyWorks jobcode

PLM:MOB02

**Comment by AnushaUp** [comment]
## Testing
Tested in `mSupply mobile v8.6.8-rc1`
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Enter dob for a patient in current year
- [ ] the age should be shown with months and days 
- [ ] If dob is more than one year then it will be shown with full number.
