### ISSUE TITLE
Remember the previous login

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/mobile#5386]
## Is your feature request related to a problem? Please describe.

When I login, I'd like the username to be populated with the most recently used username

## Describe the solution you'd like

Remember username and prepopulate

## Implementation

Local storage? Or RN alternative?

## Describe alternatives you've considered

Display a list of usernames

**Comment by GaryWilletts** [comment]
@mark-prins any idea on timeline for this? PLM Sierra Leone are asking

**Comment by mark-prins** [comment]
I tested and mobile already remembers the previous login - I had commented and closed the issue, I thought..
I thought maybe the comment was on #5394, but no. 🤷 

The other request, of displaying a list of usernames and allowing the user to pick one, a la mSupply gold - that's a lot more work and I recommend not going down that path. It's also less secure to show the possible usernames and so isn't recommended.
