### ISSUE TITLE
Show the password on the login window

### ISSUE THREAD

**Issue by GaryWilletts** [msupply-foundation/mobile#5394]
## Is your feature request related to a problem? Please describe.

Currently there is no way to know whether your password has been typed correctly.

## Describe the solution you'd like

Add an eye icon next to the password field just like the one for Open mSupply which toggles the display between dots and plain text (and the icon toggles between an eye and an eye with a line through it):

![Screenshot 2023-12-14 at 12 21 55](https://github.com/msupply-foundation/mobile/assets/11517184/c7a1eb00-41a9-47b8-831a-8da7b7b83419)

## Implementation

**A description of how the solution would best be implemented in the code base**

## Describe alternatives you've considered

None, this is the best way I can think of and it's already one we've thought is good.

## Additional context

This is for PLM Sierra Leone and they're paying for it.

## MoneyWorks jobcode
PLM:MOB01

**Comment by GaryWilletts** [comment]
@mark-prins or @arjunSussol please let me know when this will be complete so that I can let PLM know.

**Comment by mark-prins** [comment]
@GaryWilletts PR is done - we'll wait for the other change before releasing

**Comment by AnushaUp** [comment]
## Testing
Tested in `V8.6.8-rc01`
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Check that init and login still work
- [ ] And that you can show / hide the password
