### ISSUE TITLE
Blank supplier requisitions created automatically

### ISSUE THREAD

**Issue by arjunSussol** [msupply-foundation/mobile#5406]
## Describe the bug

In some of the mobile sites, blank supplier requisitions created automatically.
Ticket: https://cerb.msupply.org/profiles/ticket/18252

### To reproduce

Steps to reproduce the behaviour:

1. Get Fiji MOH data
2. Setup mobile with site `nuffield_pharm`
3. Some of the blank supplier requisitions are visible after login

### Expected behaviour

There should not be such blank records.

### Proposed Solution

Investigate and fix it.

### Version and device info

- App version:
- Tablet model:
- OS version:

**Comment by AnushaUp** [comment]
## Testing
Tested in `Mobile v8.6.6-rc01`
Steps to reproduce or otherwise test the changes of this PR:

- [ ] Get Fiji MOH data
- [ ] Setup mobile with site nuffield_pharm
- [ ] After login, there should not be any blank supplier requisitions created

**Comment by AnushaUp** [comment]
In the new release I tried forcefully deleting the supplier requisition after creating transactions linked to it and initialise again the two mobile sites CWM_ICU and Nuffield_pharm in which the problem was faced. There was no any blank requisition created. Hence PASSED.
Moving this to done.
