### ISSUE TITLE
finalised_date is blank when finalising Customer Invoice

### ISSUE THREAD

**Issue by kahn-msupply** [msupply-foundation/mobile#5534]
## Describe the bug

**CERB**: https://cerb.msupply.org/profiles/ticket/JZ-2237-HT/conversation 

When finalising a customer invoice on mobile, mSupply does not record a finalised_date. When finalising a customer invoice from mSupply desktop, the finalised_date field is populated with the date the customer invoice is finalised. 

This affects some dashboards that use the finalised_date field for mobile records.

The supplier is using tablets to process/finalize Customer Requisitions. This is not a problem for suppliers that are on mSupply desktop as customer requisitions are converted to customer invoices first before being finalized. For tablets, the customer requisition is directly finalized once data is filled in.

For dashboard reporting, In-transit flag looks at the date when customer invoices are finalized.

mSupply Desktop (Supplier) CI:

<img width="401" alt="Desktop Site" src="https://github.com/msupply-foundation/mobile/assets/132425100/9ed0305e-bbad-4991-81f0-ad809b2df314">

mSupply Mobile (Supplier) CI:

<img width="399" alt="Taveuni_HC (Mobile)" src="https://github.com/msupply-foundation/mobile/assets/132425100/7f60ae69-eea9-4923-8ed1-b1d3e2443a13">

### To reproduce

Steps to reproduce the behaviour:

1. Any datafile
2. Setup sync site for mobile
3. Create and finalise a customer invoice from mobile to any store
4. Open record browser from central and find new Customer Invoice
5. See finalised_date is 0000-00-00T00:00:00 for the finalised customer invoice

### Expected behaviour

finalised_date should be the date the invoice was finalised from mSupply Mobile.

### Proposed Solution

~

### Version and device info

- App version: 8.6.9
- Tablet model: Samsung Tablet
- OS version: Android 13

### Additional context

This could possibly be fixed from mSupply central for incoming records.

**Comment by roxy-dao** [comment]
> @JonnaQuismundo asked for this issue to be moved to desktop:
> 
> [msupply-foundation/msupply#14857](https://github.com/msupply-foundation/msupply/issues/14857)

Is there still no finalised_date even with the mSupply fix? Do you mean she asked you to move it from desktop? 🤔

**Comment by JonnaQuismundo** [comment]
@kahn-msupply can be close?

**Comment by kahn-msupply** [comment]
Yes - will close this now. Thanks team.

**Comment by marthakeezy** [comment]
No testing required so moving to Done ✅
